### ISSUE TITLE
ble-serial uses Python 3.8 specific fstring syntax which causes it to not work on Python 3.7

### ISSUE THREAD

**Issue by kylemccreery** [Jakeler/ble-serial#32]
**Describe the bug**
fstring syntax error for python 3.7 vs python 3.8. I have tested this as working on python 3.8 and reinstalled 3.7 on a new box to get this specific error output so it could be noted. This bug report is being submitted so that the supported version can be clarified on https://pypi.org/project/ble-serial/

**Log messages**
```
PS C:\Users\mccreerykr> ble-scan.exe
Traceback (most recent call last):
  File "C:\Users\mccreerykr\AppData\Local\Programs\Python\Python37\Scripts\ble-scan-script.py", line 11, in <module>
    load_entry_point('ble-serial==2.2.0', 'console_scripts', 'ble-scan')()
  File "c:\users\mccreerykr\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\mccreerykr\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "c:\users\mccreerykr\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "c:\users\mccreerykr\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\mccreerykr\appdata\local\programs\python\python37\lib\site-packages\ble_serial\__init__.py", line 8, in <module>
    from ble_serial.ports.windows_com0com import COM as platform_uart
  File "<fstring>", line 1
    (self.alive=)
               ^

SyntaxError: invalid syntax
```

**Setup (please complete the following information):**
- OS: Window 10 Pro, 10.0.19041 Build 19041
- Python Version: Python 3.7.9
- ble-serial and dependency versions: 
```
PS C:\Users\mccreerykr> pip list
Package       Version
------------- -------
ble-serial    2.2.0
bleak         0.11.0
coloredlogs   15.0
humanfriendly 9.1
pip           21.1.2
pycparser     2.20
pyreadline    2.1
pyserial      3.5
pythonnet     2.5.2
setuptools    47.1.0
```

**Comment by Jakeler** [comment]
Thanks for testing and reporting! 
I have removed the fstring= syntax now (498100910d0ada8516feeaa1886f1294c5c02860), as it is not really necessary. Should work with 3.7 as expected. Also the versions are clarified now (b71b521).
